# Generated by Django 2.0.3 on 2018-03-12 23:59

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(upload_to=accounts.models.user_directory_path)),
                ('birthday', models.CharField(blank=True, max_length=250)),
                ('city', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
