# Generated by Django 2.0.3 on 2018-03-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(db_index=True, related_name='dishes', to='cuisine.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='picture_file',
            field=models.ImageField(default='pic.png', upload_to='uploads/dishes'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='picture_file',
            field=models.ImageField(default='pic.png', upload_to='uploads/ingredients'),
        ),
    ]
