# Generated by Django 2.0.3 on 2018-04-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuisine', '0004_auto_20180319_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
        migrations.RemoveField(
            model_name='like',
            name='content_type',
        ),
        migrations.AlterField(
            model_name='dish',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.ManyToManyField(to='cuisine.Ingredient'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='picture_file',
            field=models.ImageField(default='default.jpg', upload_to='uploads/dishes'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='picture_file',
            field=models.ImageField(default='default.jpg', upload_to='uploads/ingredients'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
